### ISSUE TITLE
请求授权：）

### ISSUE THREAD

**Issue by drinktoomuchsax** [Undefinedefity/EEE5346_Course_Work#1]
学长/学姐好，能否在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及使用你的文件。会留下你的githubID以及仓库链接

**Comment by Undefinedefity** [comment]
可以用是可以用，但是我的这个repo我觉得没啥用








 


李岱峰 LI Daifeng



南方科技大学/机械与能源工程系/硕士研究生2021级



广东省深圳市南山区学苑大道1088号




E-mail: ***@***.***




Master Student of Class 2024

Department of Mechanical and Energy Engineering

Southern University of Science and Techonology, China

 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Apr 12, 2023 12:07 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[Undefinedefity/EEE5346_Course_Work] 请求授权：） (Issue #1)

&nbsp;



 
学长/学姐好，能否在SUSTech-EE-Course-Hero里引用你的项目以及使用你的文件。会留下你的githubID以及仓库链接

**Comment by drinktoomuchsax** [comment]
好的，好像受众是比较小，没关系，我看情况使用。
